### ISSUE TITLE
关于开源考虑决策？😁

### ISSUE THREAD

**Issue by ClarePhang** [sipeed/Maix-Speech#14]
Q1. 代码是否以及何时开源？

A1. star 超过[MaixPy](https://github.com/sipeed/MaixPy)项目后会考虑开源

================================================

关注很久了，都快忘记这个项目了；如今惊喜的发现，Maix-Speech 的 start 已经超过 MaixPy 不少，是否有重新考虑开源及计划？

**Comment by Neutree** [comment]
并没有超越哦，https://github.com/sipeed/MaixPy-v1 这个才是当时的 MaixPy，新的 MaixPy 是重新建的仓库

**Comment by ClarePhang** [comment]
OK，懂。生命有限我爱Python！
